### PR TITLE
Upgrade immutable to ~3.8.2

### PR DESCRIPTION
**Pull request by adamsanderson**
This tracks the most recent stable version of immutable.

As far as I can tell, there are no backwards incompatible changes.

Let me know if there is anything I can do to help you review or merge this.

### CODE REVIEW

**Comment by makenosound** [comment]
Thanks, @adamsanderson. Sorry for leaving it so long! I’ll cut a dot release for this now.

**Comment by makenosound** [comment]
Published as 2.0.3

**Comment by thibaudcolas** [comment]
Yes, again (#4) this makes this package incompatible with `draft-js`, which explicitly mandates `~3.7`.

If you want to make it possible to install either 3.7 or 3.8 versions with this package, then switch the dependency to `"^3.7.4"`, so people can have a duplicate version of Immutable.js if they want to, or chose to align with Draft.js.

**Comment by TrySound** [comment]
@thibaudcolas It's still not flexibility. Users will end with two instances of immutalbe.js in bundle. And the only way to fix it is yarn resolutions or something like webpack aliases which is very bad default.

**Comment by TrySound** [comment]
> chose to align with Draft.js.

The problem is that user cannot control installing transitive dependencies and is left without choice.

**Comment by thibaudcolas** [comment]
Just try it for yourself:

```
npm --version
# 6.14.8
mkdir test
cd test
npm init -y
npm install --save draft-js draft-js-single-line-plugin
```

Then `npm ls`:

```text
├─┬ draft-js@0.11.7
[...]
│ ├── immutable@3.7.6
├─┬ draft-js-single-line-plugin@2.0.5
│ └── immutable@3.7.6 deduped
```

That’s the expected result.

Then if someone wants to install Immutable.js 3.8, yes, they will get a duplicate Immutable.js dependency. But that’s due to the `draft-js` version requirement, not this package.

**Comment by TrySound** [comment]
Alright, I see it works in npm. Though this is not how yarn works.

**Pull request merged**
